/// Registration only writes the selected installation root. Installing the rendered
/// drop-in and restarting the role is a separate, reviewable systemd operation.
async fn register_versioned_role(
    source: UpdateSourceArgs,
    root: &Path,
    role: UpdateRole,
    binary: &Path,
) -> Result<(), CliError> {
    if matches!(role, UpdateRole::Console) || !versioned_root_valid(root) {
        return Err(CliError::invalid(
            "register requires a Control/Relay/Peer role and an absolute installation root using letters, numbers, slash, dash, underscore or dot",
        ));
    }
    let (manifest, artifact) = load_update(&source).await?;
    manifest
        .validate_candidate(
            update_now()?,
            0,
            &manifest.version,
            peerward_store::SCHEMA_VERSION,
            peerward_wire::PROTOCOL_MAJOR,
        )
        .map_err(update_error)?;
    let bytes = read_bounded_regular_file(binary, 256 * 1024 * 1024)?;
    peerward_updater::verify_artifact(&bytes, &artifact).map_err(update_error)?;
    let _lock = peerward_platform::LocalRuntimeLock::acquire(&root.join("update.lock"))
        .map_err(|error| CliError::failure(error.to_string()))?;
    let current = root.join("roles").join(role.name()).join("current");
    if UpdateTransaction::load(root, role.name())
        .map_err(update_error)?
        .is_some()
    {
        return Err(CliError::invalid(
            "an existing role transaction cannot be replaced by registration; use update status",
        ));
    }
    if fs::symlink_metadata(&current).is_ok()
        && peerward_updater::installed_role_version(root, role.name()).map_err(update_error)?
            != manifest.version
    {
        return Err(CliError::invalid(
            "this role is already registered to another version",
        ));
    }
    accept_manifest(
        &manifest,
        &root.join("accepted-update.json"),
        update_now()?,
        &manifest.version,
        peerward_store::SCHEMA_VERSION,
        peerward_wire::PROTOCOL_MAJOR,
    )
    .map_err(update_error)?;
    peerward_updater::install_versioned_release(&bytes, &artifact, &manifest, role.name(), root)
        .map_err(update_error)?;
    let document = role_dropin(root, role)?;
    let output = current.with_file_name("systemd.conf");
    if output.exists() {
        if read_bounded_regular_file(&output, 65_536)? != document.as_bytes()
        {
            return Err(CliError::invalid(
                "rendered systemd drop-in differs from the existing file; inspect it before continuing",
            ));
        }
    } else {
        write_new(&output, document.as_bytes(), false)?;
    }
    println!(
        "{}",
        serde_json::json!({"role":role.name(),"version":manifest.version,"current":current,"drop_in":output,
        "status":"staged","systemd":"not_changed","next":"install the reviewed drop-in, reload systemd, then restart this role"})
    );
    Ok(())
}

fn versioned_root_valid(root: &Path) -> bool {
    root.is_absolute()
        && root.components().count() > 1
        && root.to_str().is_some_and(|text| {
            text.len() <= 200
                && text
                    .bytes()
                    .all(|byte| byte.is_ascii_alphanumeric() || b"/._-".contains(&byte))
        })
        && root.components().all(|part| {
            matches!(
                part,
                std::path::Component::RootDir | std::path::Component::Normal(_)
            )
        })
}

fn role_dropin(root: &Path, role: UpdateRole) -> Result<String, CliError> {
    use std::fmt::Write as _;
    if !versioned_root_valid(root) || matches!(role, UpdateRole::Console) {
        return Err(CliError::invalid("invalid versioned role"));
    }
    let binary = root.join("roles").join(role.name()).join("current");
    let path = binary.display();
    let name = role.name();
    let mut contents = String::from(
        "# Generated by peerward update register; review before installation.\n[Service]\nExecStartPre=\n"
    );
    // Peer must reach its startup recovery before validating a partially
    // committed identity. Match the packaged unit when selecting a new binary.
    if !matches!(role, UpdateRole::Peer) {
        writeln!(contents, "ExecStartPre={path} config check --role {name} /etc/peerward/{name}.toml")
            .map_err(|_| CliError::failure("cannot render the role unit"))?;
    }
    writeln!(contents, "ExecStart=\nExecStart={path} {name} run --config /etc/peerward/{name}.toml")
        .map_err(|_| CliError::failure("cannot render the role unit"))?;
    if matches!(role, UpdateRole::Peer) {
        writeln!(
            contents,
            "ExecStopPost=\nExecStopPost={path} doctor --config /etc/peerward/peer.toml --json"
        )
        .map_err(|_| CliError::failure("cannot render the role unit"))?;
    }
    Ok(contents)
}

fn read_bounded_regular_file(path: &Path, maximum: u64) -> Result<Vec<u8>, CliError> {
    read_bounded_regular_file_io(path, maximum)
        .map_err(|_| CliError::invalid("input must be a bounded regular file"))
}

fn read_bounded_utf8(path: &Path, maximum: u64) -> Result<String, CliError> {
    String::from_utf8(read_bounded_regular_file(path, maximum)?)
        .map_err(|_| CliError::invalid("input is not UTF-8"))
}

#[cfg(test)]
mod update_register_tests {
    use super::*;
    #[tokio::test]
    async fn local_update_sources_obey_bounds_before_reading() {
        let directory = std::env::temp_dir().join(format!("peerward-update-input-{}", uuid::Uuid::new_v4()));
        fs::create_dir(&directory).unwrap();
        let path = directory.join("sparse-manifest");
        fs::File::create(&path).unwrap().set_len(64 * 1024 * 1024).unwrap();
        assert!(fetch_update_source(path.to_str().unwrap(), 4096).await.is_err());
        assert!(fetch_update_source(directory.to_str().unwrap(), 4096).await.is_err());
        fs::write(&path, b"bounded").unwrap();
        assert_eq!(fetch_update_source(path.to_str().unwrap(), 7).await.unwrap(), b"bounded");
        assert!(fetch_update_source(path.to_str().unwrap(), 6).await.is_err());
        fs::remove_dir_all(directory).unwrap();
    }

    #[test]
    fn rendered_units_use_only_the_selected_role_and_safe_paths() {
        for bad in [
            "relative",
            "/opt/../etc",
            "/opt/with space",
            "/opt/%n",
            "/opt/$TOKEN",
            "/opt/line\nbreak",
        ] {
            assert!(!versioned_root_valid(Path::new(bad)));
        }
        let text = role_dropin(Path::new("/opt/peerward"), UpdateRole::Peer).unwrap();
        assert!(text.contains(
            "ExecStart=/opt/peerward/roles/peer/current peer run --config /etc/peerward/peer.toml"
        ));
        assert!(text.contains("ExecStopPost=/opt/peerward/roles/peer/current doctor"));
        assert!(text.lines().all(|line| !line.starts_with("ExecStartPre=") || line == "ExecStartPre="));
        for role in [UpdateRole::Control, UpdateRole::Relay] {
            let text = role_dropin(Path::new("/opt/peerward"), role).unwrap();
            assert!(text.contains(&format!("config check --role {}", role.name())));
        }
        assert!(!text.contains("/usr/bin/peerward"));
        assert!(role_dropin(Path::new("/opt/peerward"), UpdateRole::Console).is_err());
    }
}
