fn console_routes() -> Router<AppState> {
    Router::new()
        .route(
            "/api/v1/meshes/{mesh_id}/console/enrollment-groups",
            get(console_enrollment_groups),
        )
        .route("/api/v1/console/search", get(console_search))
        .route(
            "/api/v1/meshes/{mesh_id}/console/network-resources/{resource_id}/grants",
            get(list_console_resource_grants),
        )
        .route(
            "/api/v1/meshes/{mesh_id}/console/network-resources/{resource_id}/grants/{grant_id}",
            axum::routing::put(set_console_resource_grant),
        )
        .route(
            "/api/v1/meshes/{mesh_id}/console/overview",
            get(console_overview),
        )
        .route(
            "/api/v1/meshes/{mesh_id}/console/issues",
            get(console_issues),
        )
        .route(
            "/api/v1/meshes/{mesh_id}/console/notices",
            axum::routing::patch(console_notice_update),
        )
        .route(
            "/api/v1/meshes/{mesh_id}/console/sharing",
            get(console_sharing),
        )
        .route(
            "/api/v1/meshes/{mesh_id}/console/sharing/{kind}/{id}/impact",
            get(console_sharing_impact),
        )
        .route(
            "/api/v1/meshes/{mesh_id}/console/sharing/preview",
            post(preview_console_sharing),
        )
        .route(
            "/api/v1/meshes/{mesh_id}/console/network-resources/{id}/preview",
            post(preview_console_network_edit),
        )
        .route(
            "/api/v1/meshes/{mesh_id}/console/network-resources/{id}/apply",
            post(apply_console_network_edit),
        )
        .route(
            "/api/v1/meshes/{mesh_id}/console/network-resources/{id}/gateways",
            get(console_network_gateways),
        )
        .route(
            "/api/v1/meshes/{mesh_id}/console/sharing/apply",
            post(apply_console_sharing),
        )
        .route(
            "/api/v1/meshes/{mesh_id}/console/devices",
            get(console_devices),
        )
        .route(
            "/api/v1/meshes/{mesh_id}/console/devices/export",
            get(export_console_devices),
        )
        .route(
            "/api/v1/meshes/{mesh_id}/console/devices/{peer}/activity",
            get(console_device_activity),
        )
        .route(
            "/api/v1/meshes/{mesh_id}/console/devices/{peer}/renewals",
            get(list_console_renewals).post(request_console_renewal),
        )
        .route(
            "/api/v1/meshes/{mesh_id}/console/matrix",
            post(console_matrix),
        )
        .route(
            "/api/v1/meshes/{mesh_id}/console/grants/preview",
            post(preview_console_grant),
        )
        .route(
            "/api/v1/meshes/{mesh_id}/console/devices/{peer_id}/retire",
            post(retire_console_device),
        )
        .route(
            "/api/v1/meshes/{mesh_id}/console/grants/apply",
            post(apply_console_grant),
        )
        .route(
            "/api/v1/meshes/{mesh_id}/console/services/{service_id}/grants",
            get(list_console_service_grants),
        )
        .route(
            "/api/v1/meshes/{mesh_id}/console/services/{service_id}/grants/{grant_id}",
            axum::routing::put(set_console_service_grant),
        )
        .route(
            "/api/v1/meshes/{mesh_id}/console/services/{id}",
            axum::routing::patch(edit_console_service),
        )
        .route(
            "/api/v1/meshes/{mesh_id}/console/resources/{id}/state",
            axum::routing::put(set_console_resource_state),
        )
}
