import { legacySetup } from "./legacy-setup.mjs";
legacySetup();
import { expect, test } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";
import { signedClaim } from "./join-claim.mjs";

test.skip(process.env.PEERWARD_NETWORK_MANAGEMENT_E2E !== "1", "isolated fixture required");
const origin = process.env.PEERWARD_CONSOLE_E2E_URL;

test("create invitation, verify original fingerprint and approve exactly once", async ({ page }) => {
  test.setTimeout(90_000);
  const meshes = await (await page.request.get(`${origin}/api/v1/meshes`)).json();
  const mesh = meshes.items[0].id;
  await page.goto(`${origin}/join-tickets?mesh=${mesh}`);
  await page.getByRole("dialog", { name: "Add device", exact: true }).getByRole("button", { name: "Close / 关闭", exact: true }).click();
  await page.getByLabel("Assigned device name (optional)", { exact: true }).fill("verified-browser-device");
  await page.getByLabel("Controlled labels (key=value, comma separated)", { exact: true }).fill("group=finance");
  await page.getByRole("combobox", { name: "Admission mode", exact: true }).selectOption("approval");
  await page.getByRole("combobox", { name: "Device access duration", exact: true }).selectOption("expiring");
  const deadline = new Date(Date.now() + 3_600_000).toISOString().slice(0, 16);
  await page.getByLabel("Access deadline (UTC)", { exact: true }).fill(deadline);
  await page.getByRole("button", { name: "Create", exact: true }).click();
  await expect(page.locator(".join-link")).toBeVisible();
  const link = new URL(await page.locator(".join-link").innerText());
  const bundle = JSON.parse(Buffer.from(link.searchParams.get("bundle"), "base64url").toString("utf8"));
  const path = new URL(bundle.claim_url).pathname;
  const token = path.split("/").at(-2); const claim = signedClaim(token);
  const pending = await page.request.post(`${origin}${path}`, { data: claim.body });
  expect(pending.status()).toBe(202);
  const review = page.getByRole("region", { name: "Admission requests", exact: true });
  await review.getByRole("button", { name: "Check connection", exact: true }).click();
  await expect(review.getByText("verified-browser-device", { exact: true }).first()).toBeVisible();
  const approve = review.getByRole("button", { name: "Identity matches — approve device", exact: true });
  await expect(approve).toBeDisabled();
  await review.getByLabel("Enter the full fingerprint verified on the device", { exact: true }).fill("0".repeat(64));
  await expect(approve).toBeDisabled();
  await review.getByLabel("Enter the full fingerprint verified on the device", { exact: true }).fill(claim.fingerprint);
  await approve.click();
  await expect(review.getByRole("status").filter({ hasText: "Device joined the network" })).toBeVisible();
  const first = await page.request.post(`${origin}${path}`, { data: claim.body });
  expect(first.status()).toBe(201); const response = await first.json();
  const second = await page.request.post(`${origin}${path}`, { data: claim.body });
  expect(await second.json()).toEqual(response);
  const peers = await (await page.request.get(`${origin}/api/v1/meshes/${mesh}/peers`)).json();
  const admitted = peers.items.filter(peer => peer.name === "verified-browser-device");
  expect(admitted).toHaveLength(1);
  expect(admitted[0].admission).toEqual({ kind: "expiring", valid_until: Date.parse(`${deadline}:00Z`) / 1000 });
  const accessibility = await new AxeBuilder({ page }).include('section[aria-label="Admission requests"]').analyze();
  expect(accessibility.violations).toEqual([]);
  await page.screenshot({ path: test.info().outputPath("controlled-enrollment.png"), fullPage: true });
});
