[package]
name = "peerward-directory"
description = "Canonical signed and chunked Peerward directories"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true
rust-version.workspace = true

[dependencies]
peerward-management = { path = "../peerward-management" }
ed25519-dalek.workspace = true
peerward-credentials = { path = "../peerward-credentials" }
peerward-types = { path = "../peerward-types" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
hex.workspace = true

[lints]
workspace = true
